/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'btu' at '8/26/15 5:33 PM' with Gradle 2.5
 *
 * @author btu, @date 8/26/15 5:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
